#ifndef LEGEND_ASSETS_SHADERS_MODELVIEW_MODEL_VIEW_VS_HLSL_
#define LEGEND_ASSETS_SHADERS_MODELVIEW_MODEL_VIEW_VS_HLSL_

#include "model_view.hlsli"

VSOutput main(const VSInput v ) {
	return VSMain(v);
}

#endif //! LEGEND_ASSETS_SHADERS_MODELVIEW_MODEL_VIEW_VS_HLSL_
