#ifndef LEGEND_ASSETS_SHADERS_POSTPROCESS_GRAY_SCALE_PS_HLSL_
#define LEGEND_ASSETS_SHADERS_POSTPROCESS_GRAY_SCALE_PS_HLSL_

#include "gray_scale.hlsli"


float4 main( PSInput i ) : SV_TARGET
{
	return PSMain(i);
}

#endif //! LEGEND_ASSETS_SHADERS_POSTPROCESS_GRAY_SCALE_PS_HLSL_