#ifndef LEGEND_ASSETS_SHADERS_POSTPROCESS_GRAY_SCALE_VS_HLSL_
#define LEGEND_ASSETS_SHADERS_POSTPROCESS_GRAY_SCALE_VS_HLSL_

#include "gray_scale.hlsli"


VSOutput main( VSInput v )
{
	return VSMain(v);
}

#endif //! LEGEND_ASSETS_SHADERS_POSTPROCESS_GRAY_SCALE_VS_HLSL_