#ifndef LEGEND_ASSETS_SHADERS_MULTI_RENDER_TARGET_TEST_MULTI_RENDER_TARGET_TEST_PP_PS_HLSLI_
#define LEGEND_ASSETS_SHADERS_MULTI_RENDER_TARGET_TEST_MULTI_RENDER_TARGET_TEST_PP_PS_HLSLI_

#include "multi_render_target_test_pp.hlsli"

float4 main( PSInput i ) : SV_TARGET
{
	return PSMain(i);
}
#endif //! LEGEND_ASSETS_SHADERS_MULTI_RENDER_TARGET_TEST_MULTI_RENDER_TARGET_TEST_PP_PS_HLSLI_