#ifndef LEGEND_ASSETS_SHADERS_MULTI_RENDER_TARGET_TEST_MULTI_RENDER_TARGET_TEST_VS_HLSLI_
#define LEGEND_ASSETS_SHADERS_MULTI_RENDER_TARGET_TEST_MULTI_RENDER_TARGET_TEST_VS_HLSLI_

#include "multi_render_target_test.hlsli"

VSOutput main(const VSInput v ) {
	return VSMain(v);
}

#endif //! LEGEND_ASSETS_SHADERS_MULTI_RENDER_TARGET_TEST_MULTI_RENDER_TARGET_TEST_VS_HLSLI_
