#ifndef LEGEND_ASSETS_SHADERS_MULTI_RENDER_TARGET_TEST_MULTI_RENDER_TARGET_TEST_PP_VS_HLSLI_
#define LEGEND_ASSETS_SHADERS_MULTI_RENDER_TARGET_TEST_MULTI_RENDER_TARGET_TEST_PP_VS_HLSLI_

#include "multi_render_target_test_pp.hlsli"

VSOutput main( VSInput v )
{
	return VSMain(v);
}


#endif //! LEGEND_ASSETS_SHADERS_MULTI_RENDER_TARGET_TEST_MULTI_RENDER_TARGET_TEST_PP_VS_HLSLI_